### PR TITLE
Feat/webhid

### PR DESCRIPTION
**Pull request by Julusian**
Prototype WebHID implementation

TODO - find old description..

Demo: https://streamdeck.julusian.dev/#

### CODE REVIEW

**Comment by Julusian** [comment]
@rspier I have done another round of refining of this, and have decided it is ready for publishing.
5.0.0 is published to npm under the new name https://www.npmjs.com/org/elgato-stream-deck
Could you give it a test for me? I shall be updating some uses, and once I am happy it is bug free I shall mark the old package name as deprecated on npm

**Comment by rspier** [comment]
Sorry for the delay.

I rebuilt my package with the version from NPM, and so far so good.

```
-    "@elgato-stream-deck/webhid": "link:../node-elgato-stream-deck/packages/webhid",
+    "@elgato-stream-deck/webhid": "^5.0.0",
```

- [x] Builds
- [x] Functionality Test: Works better than the previous version, I can't replicate the race condition that would sometimes result in the wrong button being painted. 

Is there any particular reason this requires Node 12?  Ubuntu 20.04 LTS still has Node 10.

All in all, looks great.  Thank you!  I'll upgrade the version on the work computer tomorrow, and "real world" test it all day.

-R

**Comment by Julusian** [comment]
> I can't replicate the race condition that would sometimes result in the wrong button being painted.

Yeah, I noticed some corruption happening when I ran the chase demo on my xl, which was a simple problem of image writes being interleaved. Was a simple fix and works real nice now :)

There are a couple of minor reasons for that.
1) node 10 is EOL at the end of april, and so will no longer be getting any security or other fixes. At that point it is longer recommended to use for anything production grade.
2) Soon after node 8 was EOL, support for it was dropped from many libraries and tools, some not even in major versions change. This made trying to maintain libraries to run on EOL versions of node is a pain. It becomes a nightmare of never updating any dependencies, and if you have to then prepare to spend some time pinning versions to get it into a valid state.
I could have left it supporting node 10 for now and done a breaking release in a few months when it becomes a problem, but I would rather not have to do a v6 release so soon.

**Comment by rspier** [comment]
I used my Streamdeck extension all day at work, and it worked great.  (I also upgraded everyone else using it, and nobody complained, for whatever that's worth.)    So from my perspective, 5.0.0 is great.

Don't worry about the node version thing, it just means it's time for me to setup nvm instead of relying on the system node.  Your rationale makes a lot of sense.

**Comment by Julusian** [comment]
That is great to hear. I need to start playing around with using the webhid part of this in things now, I know of a couple of places where it makes sense

Perfect :)

**Pull request merged**
